title: Blog
description: 小白龙的前端记录
locales:
  /:
    lang: zh-CN
    title: Blog
    description: 小白龙的前端记录
head:
  - - link
    - rel: icon
      href: /avatar.png
plugins:
  - - vuepress-plugin-helper-live2d
    - live2d:
        enable: true
        model: shizuku
        display:
          position: right
          width: 135
          height: 300
          hOffset: 30
          vOffset: 30
        mobile:
          show: false
        react:
          opacity: 0.8
themeConfig:
  logo: /avatar.png
  lastUpdated: 'LastEditTime'
  nav:
    - text: 读书笔记
      link: https://reading.xblcity.com
    - text: Github
      link: https://github.com/xblcity
  sidebar:
    - title: 介绍
      path: /
    - title: JS基础
      collapsable: false
      sidebarDepth: 2
      children:
        - /js-base/summary
        - /js-base/this
        - /js-base/call
        - /js-base/scope-closures
        - /js-base/copy
        - /js-base/inherit
        - /js-base/object-methods
        - /js-base/eventloop
        - /js-base/es6
        - /js-base/promise
        - /js-base/func-program
        - /js-base/design-mode
        - /js-base/algorithm
        - /js-base/ts-basic
        - /js-base/ts-react
    - title: JS应用
      collapsable: false
      sidebarDepth: 2
      children:
        - /js-practice/throttle
        - /js-practice/array
        - /js-practice/utils
    - title: 框架及实践
      collapsable: true
      sidebarDepth: 2
      children:
        - /react/lifecycle
        - /react/react-hooks
        - /react/redux
        - /react/redux-middleware
        - /react/complex-co
        - /library/wx-web
    - title: 前端综合知识
      collapsable: true
      sidebarDepth: 2
      children:
        - /fe-system/performance
        - /fe-system/render
        - /fe-system/http
    - title: 工程化
      collapsable: true
      sidebarDepth: 2
      children:
        - /fe-engineering/webpack-react
        - /fe-engineering/webpack
        - /fe-engineering/vs
        - /fe-engineering/git
    - title: 后端
      collapsable: true
      sidebarDepth: 2
      children:
        - /backend/little-points
        - /backend/blog
        - /backend/mysql
        - /backend/server
        - /backend/nginx
        - /backend/ubuntu
